# Generated by Django 2.2.7 on 2019-11-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20191121_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='e_to',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='n_to',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='s_to',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='w_to',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=None),
        ),
    ]
